"""Token usage tracking: one row per LLM call, per graph node, per turn."""

from __future__ import annotations

import uuid
from datetime import datetime

from sqlalchemy import ForeignKey, Index, Integer, Text
from sqlalchemy.orm import Mapped, mapped_column

from ..base import Base
from ._columns import _created_at, _uuid_pk


class TokenUsageRecord(Base):
    """One LLM call's token usage for billing / cost attribution per family.

    Columns for GROUP BY:
      family_id        – billing unit
      turn_id          – UUID string generated by lifecycle.load_context; one graph run
      thread_id        – LangGraph thread_id (conversation); nullable if not configured
      family_member_id – who triggered the turn (nullable)
      target_child_id  – which child the turn was about (nullable; may be unknown at
                         the node level, e.g. early understand calls)
      node             – graph node or capability name ("understand", "recommend", …)
      strategy         – "HEAVY" / "STANDARD" / "FAST"
      model_id         – actual model used (important when a fallback fired)
    """

    __tablename__ = "token_usage_record"

    id: Mapped[uuid.UUID] = _uuid_pk()
    family_id: Mapped[uuid.UUID] = mapped_column(
        ForeignKey("family.id"), nullable=False
    )
    turn_id: Mapped[str] = mapped_column(Text, nullable=False)
    thread_id: Mapped[str | None] = mapped_column(Text)
    family_member_id: Mapped[uuid.UUID | None] = mapped_column(
        ForeignKey("family_member.id")
    )
    target_child_id: Mapped[uuid.UUID | None] = mapped_column(
        ForeignKey("child_profile.id")
    )
    model_id: Mapped[str] = mapped_column(Text, nullable=False)
    strategy: Mapped[str] = mapped_column(Text, nullable=False)
    node: Mapped[str] = mapped_column(Text, nullable=False)
    input_tokens: Mapped[int] = mapped_column(Integer, nullable=False, default=0)
    output_tokens: Mapped[int] = mapped_column(Integer, nullable=False, default=0)
    created_at: Mapped[datetime] = _created_at()

    __table_args__ = (
        Index("idx_token_usage_family_id", "family_id"),
        Index("idx_token_usage_turn_id", "turn_id"),
        Index("idx_token_usage_thread_id", "thread_id"),
        Index("idx_token_usage_family_member_id", "family_member_id"),
    )
